export const Action = {
  GEOLOCATE: 'GEOLOCATE',
}

export const Mutation = {
  SET_LOADING: 'SET_LOADING',
  SET_GEOLOCATION: 'SET_GEOLOCATION',
  SET_REPORT_DIALOG: 'SET_REPORT_DIALOG',
  SET_DONATE_DIALOG: 'SET_DONATE_DIALOG',
  SET_MAP_OBJECT: 'SET_MAP_OBJECT',
}
