export const Action = {
  GEOLOCATE: 'GEOLOCATE',
}

export const Getter = {
  GET_UPDATE_AVAILABLE: 'GET_UPDATE_AVAILABLE',
}

export const Mutation = {
  SET_LOADING: 'SET_LOADING',
  SET_GEOLOCATION: 'SET_GEOLOCATION',
  SET_REPORT_DIALOG: 'SET_REPORT_DIALOG',
  SET_DONATE_DIALOG: 'SET_DONATE_DIALOG',
  SET_MAP_OBJECT: 'SET_MAP_OBJECT',
  SET_NAV_DRAWER: 'SET_NAV_DRAWER',
  SET_UPDATES_UNREAD: 'SET_UPDATES_UNREAD',
}
